### ISSUE TITLE
Rename Dan's mammal layers with internal IDs

### ISSUE THREAD

**Issue by andrewxhill** [andrewxhill/MOL#1]
The pipeline will not accept spec names as file names as a means of dummy proofing the pipeline in the future, so need to rename SHP file before dumping them in

**Comment by DanRosauer** [comment]
Hi there.  Can you explain this one Andrew?  The shapefile names were not species names but sequential ID numbers.  What should the preferred name format be?

**Comment by andrewxhill** [comment]
Hi Dan, this is actually an Issue for myself. Your IDs will be great for use, but I just need to write a script to convert them to our internal id's for use in our pipeline. We did it this way so that in the future it isn't so easy to mess up existing data with an erroneous name/id. The pipeline is designed to be computer usable not human usable, we will create a different layer for the system that is human usable in the future.

**Comment by andrewxhill** [comment]
Also: Our internal id's are _essentially_ GUIDs, like I was mentioning last week. They are too unwieldy for human consumption. E.g.

agdtb2wtbGFicjsLEgdTcGVjaWVzIi5hbmltYWxpYS9pbmZyYXNwZWNpZXMvYWJlZHVzX2hlcmJlcnRpX2hlcmJlcnRpDA

is 

Abedus herberti herberti

**Comment by andrewxhill** [comment]
Aaron, should we be naming the shp files by the Species kind key or the SpeciesIndex kind key?

**Comment by andrewxhill** [comment]
i'm reloading the data into the datastore so that i can query by orig authority id,

method, http://sandbox.latest.mol-lab.appspot.com/api/findid/COL/7223382

we'll see if this really works

**Comment by andrewxhill** [comment]
using google refine, pretty slick. Took dan's spreadsheet with COL Ids, turned the IDs into columns with urls that look like those in my last comment. Then simple I'm running, 'Add Column' -> 'Add Column by Fetching URLs', so nice. And tada, I should have internal keys. will finish and close if no problems.

**Comment by andrewxhill** [comment]
Okay, so I've created an api method /api/findid. It works like this
/api/findid/COL/6905991
would return the MOL ID for the AuthorityName = COL and AuthorityID = 6905991
At first I was using the datastore keys, but following Aaron's suggestion have changed to key_name for internal ids. I see a small issue with this if we ever use two authorities that recognize the same species name for different animals altogether, i.e. a bird with the same species in authority A as a mammal in authority B. Will we ever see this?

**Comment by DanRosauer** [comment]
For accepted names of vertebrates we will be fine.  The committee that looks after vertebrate names ensures that there are no duplicates.  May not be the case for synonyms.

But once we branch out to other groups there could well be duplicates.  For example there are definitely genus names which are used in both plants and insects.  So the ideal would be to make it robust to that.

**Comment by andrewxhill** [comment]
Ok, so right now it is looking okayyyyyy, since our key names include Animalia in them so no conflict with plants when we start loading them. some groups we might want to consider more refined level info.

**Comment by DanRosauer** [comment]
A good solution.  I'm still trying to remember if there could be any duplication between verts and inverts within animalia.  But if so including another higher taxon would solve it.

**Comment by andrewxhill** [comment]
I've added a 'rename.sh' file to the IUCN_mammals_polys.zip archive. It will actually rename and move all files according to the spreadsheet provided by Dan. The files that remain in the shp_google folder are those that have not been dealt with yet.

**Comment by eightysteele** [comment]
+1
