### ISSUE TITLE
GeoCommons demo of how data sources will be combined with MOL for EOL

### ISSUE THREAD

**Issue by andrewxhill** [andrewxhill/MOL#10]
Aaron and I were thinking that the time between our Feb 11th and the EOL demo, we aren't going to be able to deliver any really compelling UI. It is just out of scope for what we have done. What we can deliver is a good set of base data, a compelling story about our technology decisions, and a vision for the future. 

GeoCommons, geocommons.com, provides a very nice UI for combining external sources of mapping data. Including external tile sources. So, we think it would be very valuable to create a nice demo of say some bird expert range maps, some ornis data, and some other data such as inventory lists tied merged with geographic areas. With those, we can turn on/off layers to provide a narrative to how a user would evaluate a range map given a complete data source. 

It really helps lift the burden of jumping the gun and dumping a lot of time in UI before we are ready while at the same time giving new comers insights into how MOL will provide positive resources for the community.

**Comment by tucotuco** [comment]
+1

**Comment by ajturner** [comment]
greetings from GeoCommons - this sounded like a really interesting idea. Did you end up creating a demo UI in GeoCommons? If so, we'd love to highlight it.
