### ISSUE TITLE
Fusion Tables for layer metadata structure

### ISSUE THREAD

**Issue by tucotuco** [andrewxhill/MOL#102]
@ Though it looks quite similar, this is distinct from issue 91. In this issue, we want to manage the metadata structure for layers (not the actual layer metadata) and sources in a Fusion table.  As of now this information is taken from the two Google spreadsheet docs (http://goo.gl/UkzJW and http://goo.gl/98r46). So, we need one mollayerconfig table with columns “type, name, alias, required, indexed”.

With these tables in place the `metagen.py` script could download the CSV of the table over HTTP automatically.

Once the Fusion Table is in place. Change the reference URLs in the config.template.yaml to point to them instead of the spreadsheets.

**Comment by eightysteele** [comment]
+1

**Comment by eightysteele** [comment]
Reassigned to @gaurav.

**Comment by gaurav** [comment]
I've had a first-go at this, and it's up at running at http://www.google.com/fusiontables/DataSource?snapid=S242622v0Cy (I think I'll need to give you all access to that page; make a request and I'll add you straightaway!). I'll send out an e-mail once I've double-checked that all the rows were copied over properly and completely. There are a lot of key values missing in certain columns (FieldName, type, etc.); I propose we keep this issue open until we've sorted them out completely.

**Comment by eightysteele** [comment]
Nice! @tucotuco can confirm, but I think the schema for the Fusion Table isn't quite right and should be:

`type,name,alias,indexed,required`

`type` - the field type (dbf or source)
`name` - the field name
`alias` - the short alias name for the `name`
`indexed` - a `y` if the field is indexed and empty if not
`required` - a `y` if the field is required and empty if not

**Comment by gaurav** [comment]
Ah, I knew I'd forgotten something! I didn't want to separate the column information from the basic configuration details, so I threw everything into the Fusion Table. But I meant to create a separate view with just the columns we need for this task. Google Fusion Tables is doing a great job of maintaining the view as a separate table in the system, but treating it as a view of the complete information table, so modifying either table immediately updates the other one. The new table, to your schema, is here: http://www.google.com/fusiontables/DataSource?dsrcid=1330559

**Comment by eightysteele** [comment]
> The new table, to your schema, is here: http://www.google.com/fusiontables/DataSource?dsrcid=1330559

LGTM. Closing issue.

**Comment by tucotuco** [comment]
Yes, LGTM too.  Nice job.

On Sun, Aug 21, 2011 at 2:01 PM, eightysteele
reply@reply.github.com
wrote:
