### ISSUE TITLE
Support for Python 2.5?

### ISSUE THREAD

**Issue by gaurav** [andrewxhill/MOL#112]
Rob has made an old but fast PowerPC Mac available for me to work on Map of Life. I've managed to get [loader.py](https://github.com/gaurav/MapOfLife/blob/for-python-2.5/workflow/mol-data/loader.py) working on Python 2.5 on PowerPC, which is pretty cool, although of course the code is less elegant.

So my question is: do we want to support Python 2.5, or do we want to establish Python 2.6 as the minimum for Map of Life?

**Comment by tucotuco** [comment]
Code has been written with 2.6 as the target. We've had to do a couple of retro-active fixes to hit that target after developing in 2.7. I think we don't won't to expend effort to go backwards if there are incompatibilities. Did you have to do anything to "get loader.py working" in 2.5?

**Comment by gaurav** [comment]
Yup; it was entirely code that I'd added myself to `loader.py`. Check out @ee813c7f40 and @8b22eb3c66 for the changes I had to make. I could precisely install Python 2.6 on my work Mac, so we can make sure we stay workable in 2.6, if you think that's a good idea.

**Comment by robgur** [comment]
Following the discussion on github late in the evening here in Brussels.  Simply put, I agree we should not expend effort on backwards compatibility to 2.5 but stay in current in >= 2.6

**Comment by gaurav** [comment]
Sounds like we've got consensus - thanks everybody! I'll close down this issue now.

**Comment by eightysteele** [comment]
Just a quick comment - Python 2.5 is what App Engine runtime supports on dev_server and production. That changes in December to 2.7, so probably all good to focus on 2.6 and above.
