### ISSUE TITLE
Change species id from entity key to key name

### ISSUE THREAD

**Issue by eightysteele** [andrewxhill/MOL#12]
Currently we use Species entity keys for species ID which is kind of long, especially in URLs:
agZnZW8tZHNyDwsSBENlbGwiBTQtMC0wDA...

Change it to use Species key names like 'animalia/species/baetodes_noventus'. This approach has a few issues in terms of filenames and URLS that can be worked around.

**Comment by andrewxhill** [comment]
This is done as far as I can tell. 5 minutes ago I thought it would work well, but now I'm a bit on the fence again. 
so a url like
/tiles/animalia/species/baetodes_noventus/x/y.png 
on the remote server is okay? Sure it can work, but is it what we want? 
If yes, close it up.

**Comment by eightysteele** [comment]
> This is done as far as I can tell.

Totally. Your stuff is golden. I just pushed changes to app (mol.api) and layers (mol.service and taskqueue) and now all APIs are using the new key_name.

> /tiles/animalia/species/baetodes_noventus/x/y.png on the remote server is okay? Sure it can work, but is it what we want?

Yeah, hmmm, what don't you like about it? Right now that's how it's working and I'm cool with it unless you're thinking a mod is better. I'm totally open so either way works for me.

Changing issue label to Status-Review

**Comment by andrewxhill** [comment]
Yeah, it is going to work and I don't have any problems jumping to mind. I think this is good to close.
