### ISSUE TITLE
Map tile handler implementation on remote server

### ISSUE THREAD

**Issue by eightysteele** [andrewxhill/MOL#13]
App Engine proxies map tile requests and will download them on-demand from the remote server if not cached or datastored, so we need a map tile handler implementation on the remote server.

I'm starting work on this issue now.

**Comment by eightysteele** [comment]
Pushed the tile service:
https://github.com/andrewxhill/MOL/commit/d33a7250821da627ebe867ad52e8a21771e99412

Added regular expressions for URL params:
https://github.com/andrewxhill/MOL/commit/54eaf0bc2e4fb648ec13818940ba480106899f9c

Changing issue label from Status-Started to Status-Review.

**Comment by andrewxhill** [comment]
This also looks good. It appears that if we use the key_name for our internal ids
animalia/species/abditomys_latiden
that using them to also mean directories within the remote service, line 37 of api, will work fine.

If that is good, I think this is ready to close.

**Comment by eightysteele** [comment]
Excellent. Let's keep it open until I mod it to support the new key_name architecture.

**Comment by eightysteele** [comment]
Tile service has been updated to use the new key_name architecture. Closing issue.
