### ISSUE TITLE
Internal ID structure

### ISSUE THREAD

**Issue by andrewxhill** [andrewxhill/MOL#14]
I was thinking on the current key structure animalia/rank/value and decided I like it. We can easily mix the first variable with higher level classifications for some groups. I also like the use of the slash. The problem arose in that the slash could conflict with url and static files. But actually, maybe we can use it to our advantage and integrate it into our file storage and URL designs? So if I start processing the SHP files now, the are names like,
mam_4176.shp
which corresponds to an internal datastore key_name of
animalia/species/abditomys_latiden
so, I'll just store a shp file
in dir animalia, dir species, file abditomys_latiden.shp
which will make it a bit more structured anyway. 

Thoughts on this Aaron?

**Comment by eightysteele** [comment]
> so, I'll just store a shp file in dir animalia, dir species, file abditomys_latiden.shp

Yeah, I was thinking the _exact_ same thing. A big +1 all around.

**Comment by andrewxhill** [comment]
Seems like this has rippled through all the appropriate Issues. Done
