### ISSUE TITLE
Wiki page for high level technical architecture

### ISSUE THREAD

**Issue by eightysteele** [andrewxhill/MOL#15]
Title says it all.

**Comment by eightysteele** [comment]
I started the wiki page:
https://github.com/andrewxhill/MOL/wiki/High-Level-Technical-Architecture

It's definitely not done yet, but comments are totally welcome. I'm changing issue label to Status-Started.

**Comment by andrewxhill** [comment]
Not done for sure, but not bad enough to warrant an issue still. It will grow. Closing.
