### ISSUE TITLE
Mega denormalization

### ISSUE THREAD

**Issue by DanRosauer** [andrewxhill/MOL#18]
This is more a discussion than an issue, but I'll be interested in responses

I just processed the IUCN Amphibia range maps for 6188 species in preparation for upload to MoL.  One shapefile (7 files on disk) became 6188 shapefiles (43,316 files on disk).

Soon we'll do the same for the species lists by defined regions, turning 1 shapefile and a list into a large number of shapefiles.  There will be even more duplication because, for example, the squiggly borders or a nation or a park will be repeated for every species recorded there.

The libraries for handling items within shapefiles are easily available, as is database storage through PostGIS.

I understand that the current approach can make the handling code simpler, and that server end storage and file management are not a problem once the pipelines for automated handling are working.

But coming from a database background, where normalising data to avoid redundancy is the default approach, I'm finding this strategy a bit surprising.

So I'm sure you guys have thought this through, and it may be the best approach, but it would be good to have the discussion early on.

cheers
Dan

**Comment by andrewxhill** [comment]
I think the idea here is right, but it is not quite time for it yet. As we start to handle, for example, inventories for defined areas, then yes, this will work fine. We should curate those areas, or point to external curation, to minimize replication. But with the range maps, I fear that the goal of the project is that each range is in an independent state of flux, making denorm. very tough. Happy to keep the conversation going though.

**Comment by DanRosauer** [comment]
Makes sense.

Actually, on reflection there are two separate issues in this.

1) how we store the spatial data.
This is the question of (for example) having 1 shapefile including polygons for 4000 species v 4000 single species shapefiles.
It's awesome that the pipeline is working for the single species, so lets not mess with that.  But we may want to add an extra stage so that our tools do the work of splitting multi-species files as part of the data import pipeline.

2) what data we store
This is the normalisation (ie avoiding duplication) issue.
As you say Andrew, this is not an issue for the current expert range maps, but will be once we start on maps derived from area species lists.

2) what data we store -
