### ISSUE TITLE
GAE Metadata registration API

### ISSUE THREAD

**Issue by andrewxhill** [andrewxhill/MOL#2]
The GAE App needs an API method exclusive to the remote to register new metadata about tile layers, at the same time the metadata object shipped by the tiling pipeline should be finalized.

**Comment by eightysteele** [comment]
So I think we have these APIs in place: The MOL app running on App Engine supports registering and updating layer metadata via the REST API at '/api/layer/update'. The taskqueue running on the Colorado server hits the API with new layer metadata that are detected when it scans for new layers via the '/api/scan' REST API.

Are we missing anything in the metadata object being shipped? Currently we have: id (same entity id in the App Engine datastore), zoom, projection, date processed, bounding box coordinates, and the remote URL for tiles.

**Comment by andrewxhill** [comment]
I was working on parts of it kinda mid of your code refactoring sesh so I just couldn't remember. Awesome though, I think this is all good then.

**Comment by eightysteele** [comment]
Sweeeeeet.
