### ISSUE TITLE
Process amphibian layers

### ISSUE THREAD

**Issue by andrewxhill** [andrewxhill/MOL#24]
No one created an issue for this last week, so it has been a bit overlooked. I think it is less priority than some of the other issues we have opened. In a nutshell, the pipeline works pretty sweet, so we know in most cases it should be a matter of dropping them in to get them tiled and registered with the website. However, we have a couple of bugs and optimizations still to work on in the pipeline that it would take higher priority than adding more data first.

**Comment by DanRosauer** [comment]
The amphibian range maps and taxonomy are now ready to load.

The matching of the rangemap binomials to CoL is really good - 97% match to CoL taxonomy + synonyms

**Comment by andrewxhill** [comment]
Layers have all been processed once. I'm rerunning all of them today in the new pipeline framework. Closing.
