### ISSUE TITLE
GAE Range Map Exists API

### ISSUE THREAD

**Issue by andrewxhill** [andrewxhill/MOL#3]
Simple API that returns metadata about a range map based on Species entity key or a not found code. Will need to include information about where tiles are etc. Based on data from the metadata registration method

**Comment by andrewxhill** [comment]
We may want a more advanced, TileInfo api that gives info about what tiles exist for an species within a bounding box at some zoom, maybeeee

**Comment by eightysteele** [comment]
I've started work on this issue. Basically I'm creating a single LayerHandler for GET and PUT requests with the following API. I'm open to any changes so let me know.

To get a layer resource:

GET /layers/species_id HTTP/1.1
Host: mol-lab.appspot.com

To create a new layer resource:

PUT /layers/new_species_id HTTP/1.1
Host: mol-lab.appspot.com

To update an existing layer resource:

PUT /layers/existing_species_id HTTP/1.1
Host: mol-lab.appspot.com

**Comment by eightysteele** [comment]
@andrewxhill: Are you thinking advanced TileInfo API for prototype or down the line?

**Comment by eightysteele** [comment]
My latest work on this issue has been pushed and is ready for review. See LayersHandler on line 251 for relevant code:
https://github.com/andrewxhill/MOL/blob/modularize/app/mol/api/__init__.py

I added support for listing all layer resources:
GET /layers HTTP/1.1

Also the layers app has also been updated to hit the new layers API:
https://github.com/andrewxhill/MOL/blob/modularize/layers/layers/lib/mol/service/__init__.py

Changing issue status from 'Status-Started' to 'Status-InReview'.

**Comment by andrewxhill** [comment]
LayerHandler is looking really good. We should talk a bit about GeoPts, layer type categories, layer format (shp, tile, raster), and tile/layer versioning for some layer types

**Comment by andrewxhill** [comment]
Ok, so GeoPts are pretty flexible for search methods, so happy there.

We should use TileSetIndex.type = db.Category("Expert")

We should propose a staging of tile edits to the groups,
TileSetIndex.status = db.Category("Proposed")

TSI.errors = db.StringListProperty() where strings are JSON "{'kind':str, 'message':str}"

**Comment by eightysteele** [comment]
Added type and status properties to TileSetIndex. The Layer class in /layers is modified with new type (default 'expert') and status (default 'accepted') properties. All has been pushed:

https://github.com/andrewxhill/MOL/commit/2e58d311dee7cf0bb8e8b89d5db2690fc0f7a08f

**Comment by andrewxhill** [comment]
great, i think close! we can expand the layer type vocabulary at a later date.

**Comment by eightysteele** [comment]
+1
