### ISSUE TITLE
Refactor prototype UI code using Backbone and JQuery

### ISSUE THREAD

**Issue by eightysteele** [andrewxhill/MOL#30]
Outcome of technical architecture discussion with Sander, Andrew, and Dan during Boulder hackfest.

http://documentcloud.github.com/backbone

http://jquery.com

**Comment by eightysteele** [comment]
Complete. Code pushed. Deployed here for review:

http://unstable.mol-lab.appspot.com/search

**Comment by andrewxhill** [comment]
looking good. mustache!

**Comment by eightysteele** [comment]
Hell yeah! Grandpa loves the 'stache!

**Comment by eightysteele** [comment]
Oh, still need to bake in the range map stuff into mol.js... in progress now.

**Comment by eightysteele** [comment]
Done. Pushed and deployed:

http://unstable.mol-lab.appspot.com/search
