### ISSUE TITLE
move backend server to better machine

### ISSUE THREAD

**Issue by andrewxhill** [andrewxhill/MOL#33]
the old machine was a 4ghz single core hand me down. I'm moving everything to a more powerful machine with greater space and speed to take advantage of.

**Comment by andrewxhill** [comment]
Working well. need to debug the white background in tiles right now, strange

**Comment by eightysteele** [comment]
> the old machine was a 4ghz single core hand me down. I'm moving everything to a more powerful machine with greater space and speed to take advantage of.

Long live the old machine. She was so good to us. Sniff sniff.
