### ISSUE TITLE
MOL webpage - delete code section, dead links, simplify

### ISSUE THREAD

**Issue by walterj** [andrewxhill/MOL#35]
Now put by Dan on 
http://www.yale.edu/mapoflife/indexNew.html 
originally at http://mol.colorado.edu/.
# Please delete 'Code' section
# Keep 'Blog' section? Only if easy submissions by all are possible
# Create live (as opposed to current dead blog) link to one introduction page
# i.e. total of two pages that do work (front, background).
# How are updates done, and are they automatically applied to both URLs?

**Comment by DanRosauer** [comment]
The text on the home page under 'About MOL' is also in need of an update'.

Updates are manual.  I subscribe to the files via github and copy them across to publish the changes.

Blog updates are immediate because the blog is hosted on mol.colorado.edu and not mirrored.

**Comment by andrewxhill** [comment]
> # Please delete 'Code' section
> 
> sure, will do
> 
> # Keep 'Blog' section? Only if easy submissions by all are possible
> 
> no problem, i had built a blog into the site, but aaron and i decided it would be far less work to host the blog using an existing blogging platform externally. and now, given the limited use of back end resources at yale.edu/mapoflife i think this is the right choice even more.
> 
> # Create live (as opposed to current dead blog) link to one introduction page
> 
> yup
> 
> # How are updates done, and are they automatically applied to both URLs?
> 
> no, they will have to be pulled from github and modified to work with yale domain. I'll work to make the mods minimal for dan in the future, I hadn't thought of that. 

I'm happy to do all of these, but have been waiting for some content that Rob indicated that Walter and him would get to me. I'd like to know size of text etc before I do all the reshuffle of the front page to get rid of the coding section and then have to do it again when I get the front page text. Not to say that this web page is anything special, but making a web page look nice is one of those tasks that appears trivial until you have tried it. I'd rather not waste a lot of time reformatting, get me some content and I can get you a nearer-to-final product no problem.

'Vision' page text and outline would be great too. 
https://github.com/andrewxhill/MOL/issues#issue/6

**Comment by andrewxhill** [comment]
Old version,
http://www.yale.edu/mapoflife/indexNew.html
New version,
http://mol.colorado.edu/

response to comments:
1) Deleted code section
2) There is no blog right now, so didn't keep the blog section
3) see 2
4) only text for this one page currently, there is the tech.html in the works
5) answered previously

closing.

**Comment by walterj** [comment]
Thanks, Andrew - great.

There are still dead links at the bottom of the page. Could we remove those and retain/add links that list people / link to our respective lab webpages? 

Thanks! Walter
