### ISSUE TITLE
Synonym problem?

### ISSUE THREAD

**Issue by tucotuco** [andrewxhill/MOL#36]
Check out the synonyms listed for Acrocinus longimanus, first on the list for the following REST call:

search#q=Macropus&limit=10&offset=0&maps=false&tqx=true

Seems like a lot of spurious duplication there. Even if it is COL's fault, we should probably process that to unique values, as people will not see it as COL's fault, but ours.

**Comment by andrewxhill** [comment]
jeepers. good catch. we'll run a map reduce over all of them to get rid of all dups.

**Comment by eightysteele** [comment]
> jeepers. good catch. we'll run a map reduce over all of them to get rid of all dups.

+1

**Comment by DanRosauer** [comment]
I wonder if we should also restrict the search results to Chordata (vertebrates) for the time being so that users needn't wade through these results when searching for (in this case) a kangaroo.

----  on 2nd thoughts, perhaps the 'species with range maps' option is sufficient for now' ---

**Comment by andrewxhill** [comment]
Yeah, I think maybe we just keep it 'species with range maps', on by default

**Comment by tucotuco** [comment]
+1 to default

**Comment by andrewxhill** [comment]
@eightysteele good to close?

**Comment by jmalczyk** [comment]
Yeah might be time to close this one :)

**Comment by eightysteele** [comment]
boom, iterating FAST. closing issue.
