### ISSUE TITLE
range maps don't display anymore in Firefox and IE

### ISSUE THREAD

**Issue by walterj** [andrewxhill/MOL#38]
http://prototype.mol-lab.appspot.com
Extent displays correctly, but no maps

**Comment by eightysteele** [comment]
The latest code is deployed to the 'unstable' version here:

http://unstable.mol-lab.appspot.com/search

Are range maps displaying correctly from that link? If not, can you provide a link where you expect to see a map but do not?

**Comment by walterj** [comment]
E.g. Canadian toad (and other toads) does not display:
Anaxyrus hemiophrys

http://unstable.mol-lab.appspot.com/rangemap/animalia/species/anaxyrus_hemiophrys

**Comment by andrewxhill** [comment]
Can you tell us how a mammal looks? I have been redoing layers now that I have fixed ghost tiles, the white background, and moved the system to a different computer. That means I haven't had a chance to repopulate the amphibians. I think the browser works fine.

**Comment by walterj** [comment]
Jaguar displays fine. Lack of data for amphibians would explain lack of maps. Not a browser issue.
