### ISSUE TITLE
Point data visualization thoughts

### ISSUE THREAD

**Issue by walterj** [andrewxhill/MOL#39]
1. Taxa / synonyms. Show somewhere in window, or make available via click, all the names/synonyms that are being pulled in as points for a given species. Allow user to show different names (e.g. subspecies) in different color or to apply filter.
2. Different symbols/colors for points <1950, <1970, <2000
3. Circle size determined by spatial uncertainty
4. For points with unknown uncertainty for now apply taxon/region median and present in different color.
5. Show gradient (of color or transparency) from center to edge of circle, reflecting either linear or exponential (or …) drop-off in presence probability.
6. Think about rules how to visualize overlapping circles. May be helped by aforementioned gradient in transparency
7. These sort of thoughts useful in github, or better via email?

**Comment by DanRosauer** [comment]
Great suggestions.  If this is all feasible, would be awesome.
- perhaps use a different symbol - eg triangle - for unknown uncertainty

**Comment by andrewxhill** [comment]
Yeah, these are great. I like the triangle thought a lot.

**Comment by eightysteele** [comment]
@Walter: About item 7, I think this is perfect for GitHub issue instead of email.

**Comment by DanRosauer** [comment]
Also we can define uncertainty based on significant digits in the coordinates in some pretty obvious ways..
- if a latitude has 1 decimal place, then it has an uncertainty of at least 0.05 degrees, and gets displayed accordingly.
