### ISSUE TITLE
Dig into COL for potential error

### ISSUE THREAD

**Issue by andrewxhill** [andrewxhill/MOL#4]
See 'concolor' col search result 7
deus concolor, is that right?

Also, while at it, get Dan the column names from COL where we got synonyms

**Comment by andrewxhill** [comment]
In answer to Dan's questions,
see here,
https://github.com/andrewxhill/MOL/blob/modularize/colapp/colexport/mysql_export.py

Common names are pulled from the 'common_names' table, line 86
Synonyms are taken from 'scientific_names' based on 'is_accepted_name', line 100

Have you noticed others that I'm missing in COL?

**Comment by andrewxhill** [comment]
blarg latin1 strikes again,
https://docs.google.com/leaf?id=0B3T0pFRIJS26MWRlOTdiZWItYTJlZC00ODRlLThmZmItMjVkOTJmYTI4NWY5&hl=en&authkey=COyP8dEH

**Comment by andrewxhill** [comment]
So it doesn't appear to be a data loading issue, and a representation of the character is still on gae, but seems to break at the browser. this particular issue is fin

**Comment by eightysteele** [comment]
+1
