### ISSUE TITLE
White boxes in map for some species

### ISSUE THREAD

**Issue by walterj** [andrewxhill/MOL#40]
E.g. http://unstable.mol-lab.appspot.com/map/animalia/species/arctogalidia_trivirgata 
in both Firefox and Chrome. 
Neat you already got points into the maps - fun to explore  ... !

**Comment by andrewxhill** [comment]
mostly fixed, just a side affect of some things i'm up to. give me until the next meeting before submitting more issues about range tiles, missing or not. i should have all mammals and amphibia up by end of weekend, but will be testing, deleting, and redoing throughout.
