### ISSUE TITLE
Species ranges defined by occurrence in polygons

### ISSUE THREAD

**Issue by DanRosauer** [andrewxhill/MOL#41]
To kick off the discussion about how we handle ranges defined by region polygons, I'll lay out a very simple relational way of doing it, to get your feeback - especially Andy and Aaron on how well this will work for your architecture.

So we have 3 pieces of data:
1. a shapefile (or equivalent) for each set of regions - say one for ecoregions, for nations, for protected areas etc etc.  Each set of regions contains non-overlapping polygons, so a given location is only in one region from the set.
   These would be stored in the cloud (I assume) preprocessed for efficient display.
2. a table which integrates the shapefiles, listing the regions in each set of regions, and relevant metadata about each region, such as a full text name.
3. a table with 4 columns
       a. region set (to identify which shapefile and type of region it refers to)
       b. region (matches an ID for a polygon in the shapefile)
       c. a taxon identifier which matches the system used for the full range polygons
       d. occurence type for that taxon in that area  (at present we're just talking presence, but the system will be geared to multiple types of occurence)

The rendering could then work by turning visibility of polygons on or off for display of a given taxon.

I can see that this doesn't quite work for the current tiling system, because a given polygon may be on or off which doesn't match with a static display tile.  But there may be a way around this.

So how do we proceed?
- Can we go down this relational path?
- Or generate separate shapefiles for each species?
- Or a hybrid where we store and update data like this in back end but generate tiles for every species as is done for the current expert species ranges.

Over to you web gurus...

**Comment by tucotuco** [comment]
"Regionalisation" is confusing. Is it fair to say that this is a feature type categorisation? In other words, each shape file contains only on feature type, and that type is what is meant by the regionalisation?

**Comment by DanRosauer** [comment]
Yes.

I've edited out 'regionalisation' above to clarify.

**Comment by walterj** [comment]
At all consider Google Fusion Tables? Probably much too constrained. Here a (partial) blurb on their limitations:

Using KML for Geographic Data

You can store the geographic coordinates of points, lines, and polygons in a table by using KML. Use an INSERT or UPDATE statement to place a KML string in any column where the type has been set to Location. This is useful to create a correlation between data and locations so that the data can be visualized on a map.

When using KML syntax, be sure to avoid these common pitfalls:

```
* Do not put a space character after a comma when specifying latitude and longitude. For example, 10,10 is correct, but 10, 10 is not.
* Use upper- or lowercase exactly as shown in the syntax. For example, <Point> is correct, but <point> is not.
* Remember that the longitude comes first in KML long/lat pairs—just the opposite of the order used when specifying a lat/long pair as an ordinary string.
```

It's useful to keep in mind these limits:

```
* The total size of the data sent in one API call cannot exceed 1 MB.
* A cell of data in Fusion Tables supports a maximum of 1 million characters; it may sometimes be necessary to reduce the precision of coordinates or simplify polygon or line descriptions.
* A table may have any number of rows. However, only the first 100,000 features can be mapped.
* The ten largest-area components of a multi-geometry are shown.
```
