### ISSUE TITLE
Not all ecoregions display, e.g. >1/3/ missing for Puma concolor

### ISSUE THREAD

**Issue by walterj** [andrewxhill/MOL#47]
Hi there

I finally had time to get to the bottom of the missing ecoregions for e.g. Puma concolor. Many in C and S America that should show up do not and I just confirmed that it is not due to errors in our input file (ecoregion_species.csv in Dropbox). Both our file and check on http://gis.wwfus.org/wildfinder/ reveal 203 presence ecoregions for the species. Will email list - attachments don't seem possible in github :(.

Walter

**Comment by andrewxhill** [comment]
Fixed?
