### ISSUE TITLE
Ecoregion boundaries - if easy, delete

### ISSUE THREAD

**Issue by walterj** [andrewxhill/MOL#48]
Hi there,
If it's not too difficult, please prevent grey boundaries of individual neighboring presence ecoregions from displaying. Will be nice to show presence ecoregions as one continous surface. Eventually, we may want to show outside (but not inside) borders, but for now simply deleting all borders should be fine.

Best,

Walter

**Comment by andrewxhill** [comment]
Nope, doable but not easy right now. Gave it a shot just on puma
concolor so you could take a look at the difference.

On Mon, May 16, 2011 at 1:44 AM, walterj
reply@reply.github.com
wrote:

> Hi there,
> If it's not too difficult, please prevent grey boundaries of individual neighboring presence ecoregions from displaying. Will be nice to show presence ecoregions as one continous surface. Eventually, we may want to show outside (but not inside) borders, but for now simply deleting all borders should be fine.
> 
> Best,
> 
> Walter
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/andrewxhill/MOL/issues/48

## 

Ecology and Evolutionary Biology
University of Colorado

http://biodiversity.colorado.edu
http://biodivertido.blogspot.com

**Comment by andrewxhill** [comment]
Gone.
