### ISSUE TITLE
Search UI improvements

### ISSUE THREAD

**Issue by eightysteele** [andrewxhill/MOL#5]
Search improvements for the following UI:

http://prototype.mol-lab.appspot.com/search
1. Add a search result total record count
2. <del>Have a better page for 'no search results'</del>
3. Synonyms CSV column can be total overload
4. Add advanced search
5. <del>Browser forward/back support for results</del>
6. Sort by columns
7. <del>Choose number of results per page</del>
8. <del>Checkbox for returning only results with a range map</del>

**Comment by eightysteele** [comment]
Just pushed code for better 'no search results' (item 2) and browser history support (item 5):
https://github.com/andrewxhill/MOL/commit/7c1278c701857e7bcd82a432b009776eb48db4b3

Changing issue label to Status-Started.

**Comment by DanRosauer** [comment]
- How about option to choose number of results per page?  I was finding the 10 per page a bit small.
- Specify search term more precisely - eg starts with - so 'Rattus' wouldn't return Aphoebantus rattus

**Comment by eightysteele** [comment]
I just pushed code that adds a checkbox to the search UI (item 8) for returning only species wit a range map. It's deployed to the prototype:

http://prototype.mol-lab.appspot.com/search

So like we talked about in our Friday meeting we probably don't want to spend too much more time refining the prototype since we haven't formally started thinking about our approach to UI stuff. Do we think the prototype is currently "good enough"?

**Comment by eightysteele** [comment]
Just pushed code for the new UI architecture. You can choose the number of results per page by changing the _limit_ URL parameter. Crossing item 7 off the list of search improvements above. You can test it here:

http://unstable.mol-lab.appspot.com/search
