### ISSUE TITLE
Intermittent UI function loss

### ISSUE THREAD

**Issue by robgur** [andrewxhill/MOL#51]
There seems to be intermittent UI function losses that have to do with the "sources" and "types" states.  Occasionally, after enough times changes those states, the UI can be set to "All sources" and "All types" and only return one data type despite all being present.  I will try to more systematically reproduce this bug.

**Comment by andrewxhill** [comment]
Dude, I was trying to explain this problem to aaron one night, but
couldn't ever get it to replicate. I think he thought I had lost
it....

On Mon, May 16, 2011 at 2:29 AM, robgur
reply@reply.github.com
wrote:

> There seems to be intermittent UI function losses that have to do with the "sources" and "types" states.  Occasionally, after enough times changes those states, the UI can be set to "All sources" and "All types" and only return one data type despite all being present.  I will try to more systematically reproduce this bug.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/andrewxhill/MOL/issues/51

## 

Ecology and Evolutionary Biology
University of Colorado

http://biodiversity.colorado.edu
http://biodivertido.blogspot.com

**Comment by robgur** [comment]
Its happened more than once to me now, so I know it is a repeatable bug... 
and also.... 2:35am!!

**Comment by eightysteele** [comment]
Wow, this bug is nasty. I can't reproduce it, but I totally believe
it. I'm going to start building out the the mol.ui.Search module tests
(instead of debugging this specific issue) to see if I can surface
anything wonky. In the meantime, anyone who can reproduce will get a
round of Monkey Heads on the house.

On Mon, May 16, 2011 at 1:36 AM, robgur
reply@reply.github.com
wrote:

**Comment by eightysteele** [comment]
No progress on reproducing this bug, though I did find a couple of bugs (variable leak into global state) that _might_ have played a part here. I redeployed to our prototype URL. So def continue trying to reproduce this. If you are able to reproduce, double check that the 'All Names' link is selected and also check Chrome Developer Tools console for any JavaScript errors.

**Comment by robgur** [comment]
Good idea on using the console to check for js errors.  Will keep that open from now on.
