### ISSUE TITLE
Button to zoom into focal regions (min/max of single or all layers)

### ISSUE THREAD

**Issue by eightysteele** [andrewxhill/MOL#63]

**Comment by eightysteele** [comment]
A quick hack is done for point and range layers. If you toggle a layer (e.g., turn it off and then back on), the map will automatically zoom to the extent of the layer. Here's an example... Toggle either of the layers and you'll see what I mean:

http://goo.gl/GU9PT

Now, ecoregions and protected area layers will take longer to hack. I thiiiink we would need to combine extents for all participating polygons and then ship them to App Engine for use by the UI.

So a question for Walter and Rob would be is the zoom feature for point and range layers "good enough" for the demo? Or are ecoregion and protected area zooms essential here?

**Comment by tucotuco** [comment]
+1 to shipping predetermined outer extents to AppEngine.

**Comment by walterj** [comment]
Great, Aaron. I think this would be good for now. But after demo, we should definitely soon find a general solution that applies to all layers. A general solution _could_ be that only one zoom is available is available, that will always go to the max/min extent of the union of all data types and sources.

**Comment by eightysteele** [comment]
> I think this would be good for now. But after demo, we should definitely soon find a general solution that applies to all layers.

Agree 100%. Closing this issue as it relates to this milestone.

**Comment by eightysteele** [comment]
Via chat with Rob, the current zoom hack has some usability issues.  Proposed quick solution is a click-to-zoom button instead (next to Add, Delete, Share buttons in layer stack) that when you click, the map will zoom to extent of all selected layers. 

Reopening issue.

**Comment by eightysteele** [comment]
Added 'Zoom' button on top of layer stack. When clicked, map will zoom to combined extent of all selected layers. This is fine for demo but I don't like adding the 'Zoom' button there. Need to think on it. Closing issue pending further feedback. Deployed to:

http://demo.mol-lab.appspot.com/admin/sandbox/map

**Comment by walterj** [comment]
Zoom button takes one into the Pacific in case of Parus major.

-----Original Message-----

**Comment by eightysteele** [comment]
> Zoom button takes one into the Pacific in case of Parus major.

Yeah, zoom works right now for range maps (and soon points) but not ecoregions or protected areas (see reasons at beginning of issue). For Parus major I don't think we have any range maps (yet). Clicking zoom for unsupported types should have no effect on map zoom, so I'll make that change.

**Comment by walterj** [comment]
Not working for Rattus elaphinus, Mozilla.

**Comment by eightysteele** [comment]
> Not working for Rattus elaphinus, Mozilla. Zoom button takes one into the Pacific in case of Parus major

Done. Increased async URL fetch deadline to 10 seconds for GBIF requests. Issue was also actually related to issue #75 which has been fixed and closed. Closing this issue pending feedback. Deployed to:

http://demo.mol-lab.appspot.com/admin/sandbox/map

**Comment by walterj** [comment]
Zoom for Rattus rattus (all four data types mapped) still takes on to the middle of the Pacific (Firefox).

**Comment by walterj** [comment]
Ditto for puma concolor

**Comment by eightysteele** [comment]
> Zoom for Rattus rattus (all four data types mapped) still takes on to the middle of the Pacific (Firefox).
> Ditto for puma concolor

You're probably zooming a protected area or ecoregion? Behavior for these data types should be no zoom, checking...

**Comment by eightysteele** [comment]
Yep, that was it. Great catch guys, and thanks for the late night testing: Point and range layers zoom, protected area and ecoregion layers do not:

http://demo.mol-lab.appspot.com/admin/sandbox/map

Keeping issue closed pending further feedback.

**Comment by walterj** [comment]
Hi Aaron,

Great - thanks. I realize that part of my confusion arose from the fact that one has to actively select a layer to successfully zoom. Usually, one would simply want to zoom into the region of the world where all layers are to see what's going on, _before_ wanting to select a layer. Any chance for setting up so that when _no_ layer is selected, zoom would automatically default to expert range map?

Walter

-----Original Message-----

**Comment by eightysteele** [comment]
> zoom into the region of the world where all layers are to see what's going on, _before_ wanting to select a layer

The first time you add layers to the map, this makes sense. Now imagine you have layers on the map and you add a new layer or delete a layer. What is the zoom behavior in these cases? I would say no automatic change in zoom.

> setting up so that when _no_ layer is selected, zoom would automatically default to expert range map?

Well, maybe. My intuition though is that it's not quite right. It might be confusing to have the app start auto-zooming to specific layers without you explicitly telling it to. What do others think?
