### ISSUE TITLE
Button to select all searched and filtered layers for display

### ISSUE THREAD

**Issue by eightysteele** [andrewxhill/MOL#64]
This should work for all data types for a species.

**Comment by eightysteele** [comment]
For this I added a 'select all' link next to the 'Results' headline. Maaaaybe need a 'select none' link too. Or just a 'select all none' where 'all' and 'none' are links. It's deployed here:

http://demo.mol-lab.appspot.com/sandbox/map

Thoughts? Walter and Rob, is this sufficient for the demo?

**Comment by robgur** [comment]
How hard would it be to "select all" layers for delete from right side?  Or effectively a shift-click to select multiple layers at once.  If hard, its not essential but would be useful.  Otherwise, like the "select all" link as deployed.

**Comment by walterj** [comment]
"Select all" link as deployed is OK, but may be better placed on the right. Most intuitive would be something like "All", with button next to it, in same format as other buttons below. 
I second Rob's suggestion of a Delete All button on the right. Would really speed up switching from one species to another which is of course something one would do a lot in a demo.

**Comment by eightysteele** [comment]
> How hard would it be to "select all" layers for delete from right side?  Or effectively a shift-click to select multiple layers at once.

Done. You can now select multiple layers via shift-click. If you then click the delete button, all selected layers are deleted.

> "Select all" link as deployed is OK, but may be better placed on the right. Most intuitive would be something like "All"

Done. Renamed "select all" to "All" and moved it to the right. Also added a new "None" link that deselects all results.

Latest pushed and deployed:
http://demo.mol-lab.appspot.com/admin/sandbox/map

Looking good?

**Comment by eightysteele** [comment]
Closing this issue pending feedback.
