### ISSUE TITLE
Increase the number of GBIF points displayed

### ISSUE THREAD

**Issue by eightysteele** [andrewxhill/MOL#66]
At least 400 points would be ideal.

**Comment by eightysteele** [comment]
So I played with increasing the limit and I'm pretty confident that we can double it to 200 reliably before getting into trouble. If we go any higher, it will take App Engine too long to pull records from GBIF and things will start breaking. To get it higher we kinda get into the realm of prototyping our "all points" solution which I don't think we have time for before the demo. 

Question for Rob and Walter would be is 200 "good enough" for the purposes of the demo?

**Comment by walterj** [comment]
Thanks! Can we rely on it always pulling 200 points when there are at least 200 available? If so, then yes, in my eyes for now. We should put general solution on frontburner though for after coming week, otherwise point data type is not complete.

**Comment by eightysteele** [comment]
> Thanks! Can we rely on it always pulling 200 points when there are at least 200 available?

Definitely.

> We should put general solution on frontburner though for after coming week, otherwise point data type is not complete.

Excellent. Closing issue as it relates to this milestone.

**Comment by eightysteele** [comment]
Closing issue.
