### ISSUE TITLE
Change color of checklist areas (reserves) 

### ISSUE THREAD

**Issue by eightysteele** [andrewxhill/MOL#67]
Other than blue (e.g. violet or red). Blue is confusing with lakes.

**Comment by eightysteele** [comment]
We have a pretty dope color working for protected areas now:

http://goo.gl/y8muf

How's it look?

**Comment by walterj** [comment]
Whoa! OK, if we must :) Or polygon with black outline and hashed interior an option?

**Comment by eightysteele** [comment]
> Whoa! OK, if we must :) 

Ha! What, you don't like hot pink? :)

> Or polygon with black outline and hashed interior an option?

We could play with this, but Linode is currently migrating to a bigger instance. Maybe put this off until after demo? Or if you want to suggest a specific color (via hex code or RGB values) I can do that really quickly.

**Comment by robgur** [comment]
I think the color is fine for now if it could be made just a titch darker.  Aaron can you do that?  If yes, can we close this for the time being?

**Comment by eightysteele** [comment]
> I think the color is fine for now if it could be made just a titch darker.  Aaron can you do that?  If yes, can we close this for the time being?

Yep, I'll do it and then I'll close this issue.

**Comment by eightysteele** [comment]
Done. Here's an example of the color change:

http://ldemo.mol-lab.appspot.com/data/tile?key_name=pa-group/wdpa-group/MA133&source=WDPA&r=150&g=6&b=209&x=11&y=21&z=6

Committed and deployed to:

http://ldemo.mol-lab.appspot.com/admin/sandbox/map

Closing issue as it relates to this milestone.

**Comment by eightysteele** [comment]
Per Rob's request via chat, changed PA tile color to yellow (#FFBF00). Pushed and deployed:

http://ldemo.mol-lab.appspot.com/admin/sandbox/map
