### ISSUE TITLE
Mechanism for username/password protected access

### ISSUE THREAD

**Issue by eightysteele** [andrewxhill/MOL#68]

**Comment by eightysteele** [comment]
Let's see... Ok, so what we can probably do is just deploy the following admin-restricted URL for the demo:

http://demo.mol-lab.appspot.com/admin/sandbox/map

Then, in order to access, I'll just need to add Walter as an admin to Google App Engine. Walter, if you can send me your GMail address I'll add you. Rob, I already have yours and I'll add you too.

Is this sufficient for the demo?

**Comment by walterj** [comment]
I think so. 
My Google username is: walter.jetz@yale.edu

**Comment by eightysteele** [comment]
Ok, I just added you as an admin. You should get an email to confirm. After confirming, try accessing the link below. Success?

http://demo.mol-lab.appspot.com/admin/sandbox/map

**Comment by walterj** [comment]
Hi Aaron,

I am being asked for info for Creating an Application, an Application Identifier: and Application Title:  am I on the right track?

Walter

-----Original Message-----

**Comment by eightysteele** [comment]
> I am being asked for info for Creating an Application, an Application Identifier: and Application Title:  am I on the right track?

Hmmm... can you forward me the confirmation email you got?

**Comment by eightysteele** [comment]
Waiting for Walter to get a GMail account.

**Comment by eightysteele** [comment]
No GMail account from Walter yet, but just send it when/if you get it. Closing this issue

**Comment by walterj** [comment]
Hi Aaron,

Added an actual email account

jetz.walter@googlemail.com

to my already existing google account walter.jetz@yale.edu.

Walter

-----Original Message-----

**Comment by eightysteele** [comment]
> jetz.walter@googlemail.com

Excellent. I invited you as admin so you should get an email. After you've accepted, you should be able to access:

http://demo.mol-lab.appspot.com/admin/sandbox/map

**Comment by eightysteele** [comment]
Walter, I created a new GMail account (mol.demo.user@gmail.com), added that account as an App Engine admin on MoL, and you can now use that account to access the password protected demo. I'll email you and Rob separately with the password.
