### ISSUE TITLE
Make other data types operational for birds

### ISSUE THREAD

**Issue by eightysteele** [andrewxhill/MOL#70]
'Parus major' right now (only partial and incorrect results for ecoregion, no points).

**Comment by eightysteele** [comment]
Right, so in figuring out if we'll have time for this, we kinda need to know how soon we can get these data and also what form will they take.

**Comment by walterj** [comment]
For ecoregion and GBIF (and I think also reserve checklists) the data is already in the current sources and is queryable (query 'Parus major' or other bird species). But I am not sure it all works properly. Please check

**Comment by eightysteele** [comment]
John, can you double check this?

**Comment by tucotuco** [comment]
Parus major does return GBIF points and WWF Ecoregions. There is one issue. Two WWF Ecoregions appear in the result list for this species, but when you show them on the map, only two layers appear, leading me to believe that there is some duplication in the Ecoregion data. Checking out the hypothesis now.

**Comment by tucotuco** [comment]
So, there was a duplicate entry for WWF Ecoregion for Parus major, which doesn't seem to be universally the case. I checked Parus palustris and it had no duplicate.  Immediate solution was to remove the duplicate Parus major entry in the data store. 

So back to the original issue, it looks like GBIF Points and the WWF Ecoregion are functioning properly. Aaron to confirm and close.

**Comment by tucotuco** [comment]
Walter, can you confirm that the original issue appears fixed to you in http://demo.mol-lab.appspot.com/admin/sandbox/map please?  I see Parus major in a single WWF Ecoregion Set and I see the GBIF points for it as well.

**Comment by eightysteele** [comment]
Confirmed resolved by Walter via Skype chat.

**Comment by walterj** [comment]
Great tits work, and more.
