### ISSUE TITLE
GAE storage of remote errors

### ISSUE THREAD

**Issue by andrewxhill** [andrewxhill/MOL#8]
In the taskqueue new layer pipeline, if errors are generated we don't do anything with them. We have a couple of options,
1. write them to a file to be stored with the original data in the errors directory
2. store them in some db on the remote
3. ship them back to GAE

**Comment by andrewxhill** [comment]
I'm personally in favor of #3

**Comment by andrewxhill** [comment]
We could store it in the same metadata storage? If that is the case than if a {id}.shp is added to the watched directory any existing /tiles/{id} dir should be dropped and the metadata should be overwritten with the error in the case of an error (e.g. if we are trying to fully replace a layer with a new shp file)

**Comment by eightysteele** [comment]
Starting work on this issue. I'm in favor of option 3.

**Comment by andrewxhill** [comment]
agreed, #3 is the best way to go, we are really using GAE as the app controller, so would make sense for errors to be there

**Comment by eightysteele** [comment]
Per our chat:

TileSetIndex.errors = db.StringListProperty() where strings are JSON "{'kind':str, 'message':str}"

**Comment by eightysteele** [comment]
Here's the latest:
https://github.com/andrewxhill/MOL/commit/0de052bf6e0e714c80d6762ed1ff3052a36ff732

Changed issue status from Status-Started to Status-Review.

**Comment by andrewxhill** [comment]
This looks good to me. Closing

**Comment by eightysteele** [comment]
+1
