### ISSUE TITLE
push range map layer on top of ecoregion by default

### ISSUE THREAD

**Issue by robgur** [andrewxhill/MOL#83]
Simple change, but I think the range maps should by default have a higher z-index than the ecoregion maps.   Range maps almost always are more restricted than ecoregions, so making them appear on top of ecoregions just looks better and makes more sense.

**Comment by eightysteele** [comment]
This is related to issue #57. Adding labels Status-New and Component-UI.

**Comment by robgur** [comment]
Def.  A bit different too since it specifies default state.
