### ISSUE TITLE
Spec for layer files

### ISSUE THREAD

**Issue by eightysteele** [andrewxhill/MOL#89]
@walterj, @robgur: The spec should basically just specify metadata fields for source data and also for shapefiles (dbf et al).

**Comment by robgur** [comment]
@walterj:  The DublinCore field specifications are here: http://dublincore.org/documents/dces/.  Some or all fields are likely usable but clearly this is not complete and applies mostly to source data rather than shapefile dbfs.  Lets talk more about this soon.

**Comment by eightysteele** [comment]
@walterj, @robgur: When you have the list of fields, please specify which (if any) are required and which are optional.

**Comment by robgur** [comment]
@walterj: do you want to begin developing a list of terms and optionality/requirement asap?  Given travel, I'd prefer to do this via email but could potentially Skype or IM (ugh) if necessary

**Comment by eightysteele** [comment]
Sooner rather than later would be amazing. We're about to share the workflow spec doc related to issue #88.

**Comment by robgur** [comment]
Waiting on Walter.

**Comment by eightysteele** [comment]
@walter just posted these docs:

Metadata:
https://spreadsheets.google.com/spreadsheet/ccc?key=0AhrTNFQ9YQ4FdFFITU81WG8xZVgxR1prSWdnVnV2amc#gid=0

DBF:
https://spreadsheets0.google.com/spreadsheet/ccc?key=0AhrTNFQ9YQ4FdE91SXdfT20ybFVxNXVQU2pteFpuVlE#gid=0

**Comment by eightysteele** [comment]
@walter: Thanks! Indeed I meant @walterj.

**Comment by eightysteele** [comment]
Done! Closing issue.
