### ISSUE TITLE
Assign FieldName to Dublin or Darwin Core

### ISSUE THREAD

**Issue by eightysteele** [andrewxhill/MOL#92]
In the `FieldName` column standardize value to Dublin or Darwin Core where possible for both schema docs. All names should have no spaces.

**Comment by tucotuco** [comment]
Both spreadsheets filled in for field and standard they come from.

**Comment by eightysteele** [comment]
DBF `FieldName` values LGTM, but there are still some blank `FieldName` values in the MOLSourceFields doc: http://goo.gl/cB4ps

**Comment by eightysteele** [comment]
@tucotuco: BTW, during the meeting I wrote down that we decided to just name `FieldName` the same as `Field` but without spaces (or something different if it's more readable).

**Comment by tucotuco** [comment]
@walterj @robgur: I have filled in field names and the standards they come from (or not) for both spreadsheets. I have also added comments to a bunch of them, either with questions or recommendations. This could all use a review.

**Comment by gaurav** [comment]
I'll have a look at the remaining field names in the Fusion Table this week, and see if we can assign them to DC or DwC.

**Comment by tucotuco** [comment]
I've got a view open to look at this and could bang it out quickly. I see some terms that say they have MoL as an origin (e.g, Common Name) that exist in DwC (e.g., as vernacularName), and others that already exist in DC (e.g., rights). Will do if you want me to.

**Comment by gaurav** [comment]
@tucotuco Sure, thanks! I'm sure you'll be able to go through this much faster than I would, and it'd be great to have feedback on how the FusionTable/validation/metadata database interactions are working. Feel free to reassign it back to me if you end up not having the time. So far, I'm treating this as another bug that can wait until after TDWG.

**Comment by tucotuco** [comment]
Done.

**Comment by gaurav** [comment]
The `config.yaml` files and `bulkload_helper.py` now validate to @tucotuco's new field specification. Thanks, @tucotuco! This bug is sorted.

**Comment by tucotuco** [comment]
+1
